"""Artifact definitions for inter-agent communication."""

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field


class GitLabEntity(BaseModel):
    """Base class for GitLab entities."""

    id: int
    web_url: str
    created_at: datetime
    updated_at: datetime


class Issue(GitLabEntity):
    """GitLab issue artifact."""

    iid: int
    project_id: int
    title: str
    description: Optional[str] = None
    state: str
    labels: list[str] = Field(default_factory=list)
    author: dict[str, Any]
    assignees: list[dict[str, Any]] = Field(default_factory=list)
    milestone: Optional[dict[str, Any]] = None


class MergeRequest(GitLabEntity):
    """GitLab merge request artifact."""

    iid: int
    project_id: int
    title: str
    description: Optional[str] = None
    state: str
    source_branch: str
    target_branch: str
    author: dict[str, Any]
    assignees: list[dict[str, Any]] = Field(default_factory=list)
    reviewers: list[dict[str, Any]] = Field(default_factory=list)
    merged_at: Optional[datetime] = None


class Pipeline(GitLabEntity):
    """GitLab pipeline artifact."""

    iid: int
    project_id: int
    status: str
    ref: str
    sha: str
    source: Optional[str] = None


class Job(GitLabEntity):
    """GitLab CI job artifact."""

    pipeline_id: int
    name: str
    stage: str
    status: str
    ref: str
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    duration: Optional[float] = None


class IssueSummary(BaseModel):
    """Summary of an issue generated by an agent."""

    issue_iid: int
    project: str
    title: str
    summary: str
    key_points: list[str] = Field(default_factory=list)
    status: str
    priority: Optional[str] = None
    complexity: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class MergeRequestSummary(BaseModel):
    """Summary of a merge request generated by an agent."""

    mr_iid: int
    project: str
    title: str
    summary: str
    changes_summary: str
    review_status: str
    recommendations: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class CodeReview(BaseModel):
    """Code review analysis."""

    mr_iid: int
    project: str
    overall_assessment: str
    issues_found: list[dict[str, Any]] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    approval_recommendation: bool
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class PipelineAnalysis(BaseModel):
    """Pipeline failure analysis."""

    pipeline_id: int
    project: str
    status: str
    failed_jobs: list[str] = Field(default_factory=list)
    root_cause: Optional[str] = None
    recommendations: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
